### PR TITLE
tests: allow -j to work

### PR DESCRIPTION
**Pull request by chrissie-c**
This makes the IPC tests all run as one serial test. Having start, test, end as separate tests was a daft idea anyway.

It would be helpful to run ipc.test and ipc_sock.test in parallel (especially as they are the most time-consuming), but that's another project for now.

### CODE REVIEW

**Comment by chrissie-c** [comment]
retest this please

**Comment by chrissie-c** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Comment by fabbione** [comment]
retest this please

**Review by fabbione — APPROVED** [review]

**Pull request merged**
