### PR TITLE
Fix comment typo

### PR DESCRIPTION
**Pull request by wferi**
Or there may be an explanation instead: according to socket(7), the
Linux kernel doubles the set value "to allow space for bookkeeping
overhead [...] and this doubled value is returned by getsockopt(2)."
In other words, this really is some kernel buffer size, not the size
of the biggest packet possible to send (as far as I understand it).
Note that BSD does not do this doubling.

Signed-off-by: Ferenc Wágner <wferi@debian.org>

### CODE REVIEW

**Comment by wferi** [comment]
I will do that.
Shouldn't the code change as well to account for the bookkeeping overhead on BSD? Or does BSD not need extra buffer space?

**Comment by chrissie-c** [comment]
Thanks.

It's a fair point about BSD and the true answer is that I don't know, but we haven't had any problems reported. So maybe it does its own bookkeeping behind the scenes?

**Comment by wferi** [comment]
@chrissie-c , why did you close this PR?

**Comment by chrissie-c** [comment]
Total mistake, please accept my apologies!

**Comment by wferi** [comment]
I'll put the socket buffer stuff into a new PR and keep this one for typos.

**Comment by chrissie-c** [comment]
Fair enough! Are there others to come is is this ready for pulling?

**Comment by wferi** [comment]
Sorry for the delay! I haven't got more typo fixes queued at the moment. Shall I rebase this to current master?

**Comment by chrissie-c** [comment]
Yes please, then I'll pull it and we can get on with our lives :)

**Comment by wferi** [comment]
Done.

**Comment by chrissie-c** [comment]
Thanks!

**Pull request merged**
