### PR TITLE
High: yield to scheduler during connection processing

### PR DESCRIPTION
**Pull request by davidvossel**

### CODE REVIEW

**Comment by davidvossel** [comment]
@chrissie-c okay. I removed the recvmsg spin entirely by letting mainloop handle the file descriptor. Give the updated patch a shot.

**Comment by davidvossel** [comment]
@michael-dev see if this helps you out as well

**Comment by michael-dev** [comment]
Thankyou very much, this helps me as well.

**Comment by chrissie-c** [comment]
Yes, that works for me too. Thanks

**Pull request merged**
