### PR TITLE
Memleak fixes

### PR DESCRIPTION
**Pull request by jnpkrn**
WIP, do not pull yet.

### CODE REVIEW

**Comment by jnpkrn** [comment]
Actually I found another instance of missing `free(base_name);` and also
moved `sock_name` free'ing rather to `ESTABLISHED || ACTIVE` that feels
a right place for that.  Once being head down to that part, I've also
added some clarification to something that IMHO should have been clarified
for ages (magic constants are bad, alright?).

**Comment by jnpkrn** [comment]
Also, the reason for CI failure is clear: their 64 MB sized /dev/shm gets full easily.

**Comment by chrissie-c** [comment]
We need to look into the CI and test failures. If they fail randomly like this then they are worse than useless.

**Comment by chrissie-c** [comment]
But the patch is good, I'll include it in the upcoming release. Thanks!

**Comment by jnpkrn** [comment]
Yes, I've been meaning to add a parallel run to the test suite with
abstract sockets kill-switch enabled.

Regarding the intermittent failures when /dev/shm is full, we should
at least lean towards better reporting of that condition in libqb
itself -- there's no guarantees this won't happen in production use.

**Pull request merged**
