### PR TITLE
[version_1] Set correct ownership if qb_ipcs_connection_auth_set() has been used

### PR DESCRIPTION
**Pull request by diabonas**
Backport #381 in case there is another 1.0.* release.

### CODE REVIEW

**Comment by diabonas** [comment]
The CI failure comes from a [linting error](https://travis-ci.org/ClusterLabs/libqb/jobs/648347719#L1914) that appears to be unrelated to the proposed patch.

**Comment by chrissie-c** [comment]
It looks good to me. Can you fix the split errors please? it's just a question of changing the line in lib/Makefile.am from " 2 code warnings" to " 3 code warnings", then I'll pull it.

Thanks!

**Comment by diabonas** [comment]
Thanks, I didn't realise the linting error was due to the ignored return value of `chown()`, on my system `run_splint.sh` fails with completely unrelated error messages. I amended the commit and force-pushed - not quite sure why CI is failing this time, it passed in [my own Travis CI namespace](https://travis-ci.com/diabonas/libqb/builds/148589303)...

**Comment by chrissie-c** [comment]
Thanks for that. The RPM build fail is 'normal' so that I'm not going to worry about!

**Pull request merged**
