### PR TITLE
ipc: fix compile warning on non-Linux platforms

### PR DESCRIPTION
**Pull request by chrissie-c**
Signed-off-by: Christine Caulfield <ccaulfie@redhat.com>

### CODE REVIEW

**Comment by kgaillot** [comment]
looks good to me

**Comment by jnpkrn** [comment]
I think that for platforms beside `QB_LINUX` and `QB_CYGWIN` it should
not even go through is-initiated part but return constant right away,
which the compiler can optimize out right away (perhaps with a hint
when the function is `inline`, which it is a good candidate for anyway).

Otherwise the fix is sound.

**Comment by chrissie-c** [comment]
True, but it's not on the fast path.

**Comment by jnpkrn** [comment]
I don't understand.

**Comment by chrissie-c** [comment]
It's only called when the socket is created (at either end), so quite infrequently. Optimisation is not going to achieve much.

**Comment by jnpkrn** [comment]
True.  Except for the test suite and similar "rapid" use cases.

**Comment by chrissie-c** [comment]
The test suite has bigger problems ;-)

**Pull request merged**
