### PR TITLE
Handle errno properly

### PR DESCRIPTION
**Pull request by kgaillot**
I noticed some trivial bugs. I haven't done any testing.

### CODE REVIEW

**Comment by fabbione** [comment]
add to whitelist

**Comment by jnpkrn** [comment]
Good catches, Ken, received green in my book.

I dared to push another on-topic change (for the first time ever,
making me rethink my own stance to "maintainer can add commits",
open to discussion whether it's more beneficial model overall),
please counter-review.

**Comment by kgaillot** [comment]
> I dared to push another on-topic change (for the first time ever,
> making me rethink my own stance to "maintainer can add commits",
> open to discussion whether it's more beneficial model overall),
> please counter-review.

Looks fine to me.

CI is failing b/c version is empty in the spec for some reason

**Comment by chrissie-c** [comment]
retest this please

**Comment by chrissie-c** [comment]
All look good to me, thanks. I'll just run it through the Jenkins CI again.

**Comment by chrissie-c** [comment]
Merged, thanks

**Pull request merged**
