### PR TITLE
RFC:  ipcc: Add an async connect API

### PR DESCRIPTION
**Pull request by chrissie-c**
DO NOT pull yet, this is for review & CI only at this stage.

### CODE REVIEW

**Comment by wenningerk** [comment]
Simple prototype of pacemaker using the new async connect API
for subprocess supervision seems to do the trick:

https://github.com/ClusterLabs/pacemaker/pull/2588

**Review by wenningerk — APPROVED** [review]
As said looking good as far as I can tell.
And prototype in pacemaker built upon the async connect API is looking good so far as well.

**Comment by fabbione** [comment]
retest this please

(testing CI and github branch renaming)

**Comment by fabbione** [comment]
retest this please

(testing CI and github branch renaming)

**Comment by fabbione** [comment]
retest this please

(testing CI and github branch renaming)

**Pull request merged**
