### PR TITLE
Build: prefer XZ tarball format

### PR DESCRIPTION
**Pull request by jnpkrn**

### CODE REVIEW

**Comment by jnpkrn** [comment]
@fabbione warned this could be troublesome on BSD, real test is currently pending

**Comment by jnpkrn** [comment]
Tested with FreeBSD 10.2 VM [1], without a glitch.

[1] ftp://ftp.freebsd.org/pub/FreeBSD/releases/VM-IMAGES/10.2-RELEASE/amd64/Latest/

what was needed:

```
for p in git autoconf automake libtool gmake libcheck pkgconf gcc; do
    pkg install $p
done
git clone https://github.com/jnpkrn/libqb.git
cd libqb
git checkout build-prefer-xz
./autogen.sh
MAKE=gmake ./configure
gmake dist
ls *.tar.*
```
with a result:
```
libqb-1.0rc2.51-df5e.tar.gz	libqb-1.0rc2.51-df5e.tar.xz
```

After this:
```
gmake clean-generic
ls *.tar.*
```
with a result:
```
ls: *.tar.*: No such file or directory
```

Hence I conclude that using fairly recent FreeBSD, there is no issue.

**Comment by jnpkrn** [comment]
```
pkg install rpm4
# from within libqb directory from previous comment
rm -rf *
git checkout .
./autogen.sh && MAKE=gmake ./configure && MAKE=gmake gmake srpm
ls *.rpm
```
worked as well:
```
libqb-1.0rc2-1.51.df5e.src.rpm
```

**Comment by fabbione** [comment]
On 03/09/2016 06:29 PM, Jan Pokorný wrote:
> |pkg install rpm4 # from within libqb directory from previous comment rm
> -rf * git checkout . ./autogen.sh && MAKE=gmake ./configure &&
> MAKE=gmake gmake srpm ls *.rpm |
> 
> worked as well:
> 
> |libqb-1.0rc2-1.51.df5e.src.rpm |
> 

ACK, please merge.

Fabio

**Comment by chrissie-c** [comment]
I've also tested this on NetBSD 7 and OpenBSD 5

**Pull request merged**
