### PR TITLE
WIP: Hurd portability

### PR DESCRIPTION
**Pull request by wferi**

### CODE REVIEW

**Comment by chrissie-c** [comment]
This failed CI on the monotonic check. Can you fix please?

**Comment by wferi** [comment]
Yes, I know, this only works on Hurd at the moment (thus the WIP tag). Looks like it isn't possible to check for a working monotonic clock at configuration or even compile time, but a runtime check will be needed, because for example on x86 `_POSIX_MONOTONIC_CLOCK` is defined to 0 (ask `sysconf`). Also, on Hurd `CLOCK_MONOTONIC` is actually `CLOCK_REALTIME` behind the scenes. I'm not sure how much effort this mess warrants at the end of the day.

**Comment by wferi** [comment]
The monotonic stuff is more involved and mostly independent, let's separate it out.

**Comment by wferi** [comment]
Wait, something funny is still going on with the permissions...

**Comment by wferi** [comment]
Nevermind, it was a chroot artifact.

**Pull request closed without merging**
