### PR TITLE
master: Issue 390: Clarify documentation of qb_loop_timer_expire_time…

### PR DESCRIPTION
**Pull request by cmurphycode**
…_get and provide new function to return previously documented behavior

As discussed in https://github.com/ClusterLabs/libqb/issues/390. I'm not delighted with how this turned out (lots of shared code) but here goes anyway. It compiles...sorry, I'm not familiar with your testing.

Thanks!

### CODE REVIEW

**Comment by chrissie-c** [comment]
Thanks. I  also propose this addition to the unit tests

```
diff --git a/tests/check_loop.c b/tests/check_loop.c
index ac9bbbf..81cc2ba 100644
--- a/tests/check_loop.c
+++ b/tests/check_loop.c
@@ -348,6 +348,22 @@ static Suite *loop_job_suite(void)
  *  Timers
  */
 static qb_loop_timer_handle test_th;
+static qb_loop_timer_handle test_th2;
+
+static void check_time_left(void *data)
+{
+	qb_loop_t *l = (qb_loop_t *)data;
+
+	/* NOTE: We are checking the 'stop_loop' timer here, not our own */
+	uint64_t abs_time = qb_loop_timer_expire_time_get(l, test_th);
+	uint64_t rel_time = qb_loop_timer_expire_time_remaining(l, test_th);
+
+	ck_assert(abs_time > 0ULL);
+	ck_assert(rel_time > 0ULL);
+	ck_assert(abs_time >  rel_time);
+	ck_assert(rel_time <= 60*QB_TIME_NS_IN_MSEC);
+}
+
 
 START_TEST(test_loop_timer_input)
 {
@@ -409,6 +425,9 @@ START_TEST(test_loop_timer_basic)
 	res = qb_loop_timer_add(l, QB_LOOP_LOW, 7*QB_TIME_NS_IN_MSEC, l, reset_one_shot_tmo, &reset_th);
 	ck_assert_int_eq(res, 0);
 
+	res = qb_loop_timer_add(l, QB_LOOP_HIGH, 20*QB_TIME_NS_IN_MSEC, l, check_time_left, &test_th2);
+	ck_assert_int_eq(res, 0);
+
 	res = qb_loop_timer_add(l, QB_LOOP_LOW, 60*QB_TIME_NS_IN_MSEC, l, job_stop, &test_th);
 	ck_assert_int_eq(res, 0);
 

```

**Comment by cmurphycode** [comment]
@chrissie-c Thanks for the test! I added it and amended the original commit.

**Comment by chrissie-c** [comment]
retest this please

**Comment by chrissie-c** [comment]
retest this please

**Comment by chrissie-c** [comment]
Merged, thanks!

**Pull request merged**
